repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # use latest compatible version
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5  # use latest version of Ruff
    hooks:
      - id: ruff